spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oriontek_db
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      [indent_output]: true

server:
  port: 8080

springdoc:
  [api-docs]:
    path: /api-docs
  [swagger-ui]:
    path: /swagger-ui.html
